- laravel/resources/views/pages/about.blade.php
- laravel/resources/views/pages/home.blade.php
Update the home and about pages with 2016 Art Grant information.
> Update home and about pages

- laravel/app/Http/Controllers/AnswerController.php
- laravel/app/Http/Controllers/DocumentController.php
- laravel/app/Http/routes.php
- laravel/app/Models/Document.php
- laravel/resources/views/pages/applications/view.blade.php
Set of changes to update file uploads for question and generic upload support.
> Update file upload 

- laravel/resources/views/pages/applications/review.blade.php
Allow judges to see the uploaded files during review.
Signed-off-by: Marc Jones <marcj303@gmail.com>
> Add files to the review view

- laravel/app/Http/Controllers/FeedbackController.php
- laravel/resources/views/pages/applications/review.blade.php
- laravel/resources/views/pages/feedback/create.blade.php
- laravel/resources/views/partials/applications/feedback-form.blade.php
> Feedback and file upload updates.

- laravel/app/Http/Controllers/FeedbackController.php
- laravel/resources/views/pages/applications/list.blade.php
- laravel/resources/views/pages/applications/review.blade.php
- laravel/resources/views/pages/dashboard.blade.php
- laravel/resources/views/pages/feedback/create.blade.php
- laravel/resources/views/pages/users/view.blade.php
Several little improvements for viewing users and applications.
Add list of applications in the user view
Default feedback type to textarea
Add more application information to the review blade
Add application time to the date reporting
Update app list view for application status
Fix typo in Feedback controller comment
> Several little improvements for viewing users and applications. Take2

- laravel/app/Models/Score.php
- laravel/resources/views/pages/applications/create.blade.php
- laravel/resources/views/pages/applications/list.blade.php
- laravel/resources/views/pages/applications/review.blade.php
- laravel/resources/views/pages/applications/view.blade.php
Comments and changes welcome.
changes:
Clarify the application buttons
Remove errant ) from the review blade  
Fix judge criteria score in review blade  
Score objective N/A criteria as a YES 
Add link to user profile in application blade
> Small improvements

- laravel/resources/views/pages/applications/review.blade.php
- laravel/resources/views/pages/home.blade.php
- laravel/resources/views/partials/applications/feedback-form.blade.php
Add Login button on the home page	
Add button for feedback response	#40
Indicate if a user has not responded to feedback
Add judges names to their feedback questions
> Interface tweaks based on user feedback. 

- laravel/app/Http/Controllers/DocumentController.php
- laravel/app/Providers/AuthServiceProvider.php
- laravel/resources/views/pages/applications/review.blade.php
Add link to user profile in the review blade
Allow admins to upload files to applications
> let admins add files and put a link to the user on the review blade.

- laravel/app/Http/Controllers/ScoreController.php
- laravel/app/Http/routes.php
- laravel/app/Models/Score.php
- laravel/app/Providers/AuthServiceProvider.php
- laravel/resources/views/pages/applications/list.blade.php
- laravel/resources/views/pages/applications/listscores.blade.php
- laravel/resources/views/pages/applications/scores.blade.php
- laravel/resources/views/partials/header.blade.php
Add two new views:
listscores blade (/scores): List all the applications with
average score for each criterion.
score blade (/scores/{{application_id}}: List each judge's score
for an criterion.
Signed-off-by: Marc Jones <marcj303@gmail.com>
> Add Score views

- laravel/resources/css/_review.scss
- laravel/resources/css/main.scss
- laravel/resources/views/pages/applications/review.blade.php
- laravel/resources/views/partials/applications/feedback-form.blade.php
Reorganize the review view and make it responsive
Reorganize the review view as follows:
1. Group general feedback with the project summary
2. Group question feedback below each question
3. Put the judge scoring on the right hand side
4. Make the questions area scroll for easier review
while scoring.
Use the bootstrap fluid row and column responsive  css to
work with all types of screens.
> Reorganize the review view and make it responsive

- laravel/resources/views/pages/applications/review.blade.php
Don't scroll applicant review page
Fix buttons overlap with footer
> A few minor fixes for the review view

- laravel/app/Http/Controllers/ApplicationController.php
- laravel/app/Http/routes.php
- laravel/resources/css/_review.scss
- laravel/resources/views/pages/applications/review.blade.php
Set boarder and text to red on application warnings
Add application withdraw feature
Fix @endunless in the review blade
> Additional features for review view - warnings and withdraw

- laravel/app/Http/Controllers/ApplicationController.php
- laravel/app/Http/Controllers/PageController.php
- laravel/app/Http/Controllers/ScoreController.php
- laravel/resources/css/_general.scss
- laravel/resources/css/_review.scss
- laravel/resources/views/pages/applications/list.blade.php
- laravel/resources/views/pages/applications/review.blade.php
- laravel/resources/views/pages/dashboard.blade.php
- laravel/resources/views/pages/scores/list.blade.php
Default sort applications by total score  …
Display applications and scores by round  …	
Make hover color yellow  …
Add scrollable CSS class  …
Rename review CSS h-scroll class to y-scroll  …
Scroll and stripe application and score tables  …
Add score columns to application and score views  …
Display users application view by round  …
> Update application and score tables for easier reading

- laravel/resources/views/pages/applications/create.blade.php
- laravel/resources/views/pages/applications/review.blade.php
- laravel/resources/views/pages/applications/view.blade.php
- laravel/resources/views/pages/dashboard.blade.php
- laravel/resources/views/pages/register.blade.php
- laravel/resources/views/pages/users/list.blade.php
- laravel/resources/views/pages/users/view.blade.php
A few things to make remind users and judges lives better.
Make user email address mailto: links
Add username to application list on judges dashboard 
Add helpful links to the application 
Add login and forgot links in the user register view
> Littledetails

- laravel/app/Http/Controllers/ApplicationController.php
- laravel/app/Http/Controllers/ScoreController.php
- laravel/app/Models/Score.php
- laravel/database/migrations/2017_01_19_125656_add_abstain_to_judged.php
- laravel/database/migrations/2017_01_19_163153_change_score_to_double.php
- laravel/resources/views/pages/applications/review.blade.php
Judges may abstain from an application. This also updates
the scores to calculate the average score and removes any
effect the abstain previously had.
Issue #43
> Allow judges to abstain from scoring an application

- laravel/app/Http/Controllers/PageController.php
The worklist had a bug in the join where any judge score
would hide the application instead of only the current
judged score.
I couldn't figure out how to make it work in a single
eloquent statement. I had to resort to two database queries.
Signed-off-by: Marc Jones <marcj303@gmail.com>
> Fix judge dashboard "worklist"

- laravel/app/Http/Controllers/ApplicationController.php
- laravel/app/Http/routes.php
- laravel/resources/views/pages/applications/create.blade.php
- laravel/resources/views/pages/dashboard.blade.php
Took @Meleeman01's frontend changes and updated the backend to support applying to individual rounds.
> Individual round buttons

- laravel/resources/views/pages/dashboard.blade.php
yup.
i'm not sure if this is what he wants, but creating an application and applying for grants sounded like the same thing. so I did that. i apologize for any misunderstanding.
> created apply buttons for each grant round

- laravel/app/Http/Controllers/ReportsController.php
possible fix to real_name bug. though I've been able to input data without a real_name. i'm not sure what unique thing you did, but if you could do it again, or show me how to do it i'm good. as this is time sensitive i'll pass this code to you.
> Added applicant_email to be exported to CSV. 

- laravel/app/Http/Controllers/UserController.php
- laravel/resources/views/pages/users/list.blade.php
while creating the search function it interfered with the paginate function on listUsers(). As a result of checking if the links exist, whenever a user would do a search the pagination will disappear. I can see if I can rectify that behavior if it is undesireable.
> Added a search feature for the user-list view.

- laravel/.env.example
- laravel/app/Console/Commands/CheckSigStatus.php
- laravel/app/Console/Commands/CreateSignature.php
- laravel/app/Console/Kernel.php
- laravel/app/Http/Controllers/SignatureController.php
- laravel/app/Models/Signature.php
- laravel/database/migrations/2023_01_10_050834_create_signature_table.php
Per your request, trying to combine changes across forks.
> Repairs for updates for 2024

- laravel/.env.example
- laravel/app/Http/Controllers/SignatureController.php
Fixed issue with error on API call and then also added a message.
> Fixes and email message for Doc Seal
